branches:
  only:
  - master

image:
- Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

build_script:
  - cmd: cd C:\projects\service
  - cmd: mkdir build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR=Visual Studio 15 2017
  - cmd: if "%platform%"=="x64" set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
  - cmd: cmake -G"%CMAKE_GENERATOR%" ..
  - cmd: msbuild service.sln /p:Configuration=%configuration% /p:Platform=%platform%
