configuration:
  - Debug
  - Release

platform:
  - x64

init:
  - cmd: cmake --version
  - cmd: msbuild /version

build_script:
  - cmd: cd C:\projects\service
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=%configuration% ..
  - cmd: msbuild service.sln
