environment:
  matrix:
    - CMAKE_BUILD_TYPE: Debug
    - CMAKE_BUILD_TYPE: Release

platform:
  - x64

init:
  - cmd: cmake --version
  - cmd: msbuild /version

build_script:
  - cmd: cd C:\projects\service
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ..
  - cmd: msbuild service.sln
