environment:
  matrix:
    - CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    - CMAKE_GENERATOR: Visual Studio 14 2015

platform:
  - x64

init:
  - cmd: cmake --version
  - cmd: msbuild /version

build_script:
  - cmd: cd C:\projects\service
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"%CMAKE_GENERATOR%" ..
  - cmd: msbuild service.sln
